### ISSUE TITLE
Multiple repos and an overall confusing mess

### ISSUE THREAD

**Issue by AlexDaniel** [stancecoke/BMSBattery_S_controllers_firmware#16]
When trying to figure out what's going on with this project it's very hard and confusing.
* There's an old repo here: https://github.com/OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware
* New repo here: https://github.com/stancecoke/BMSBattery_S_controllers_firmware
* However, the repos have diverged a lot. This repo is 407 commits ahead, *but 236 commits behind*. So I'm really wondering what happened in these 236 (!) commits, e.g. are there any features there that don't exist here?

Then there's documentation:
* This website which you can sometimes find via google: https://opensourceebikefirmware.bitbucket.io/windows_instructions
* This documentation (also on bitbucket) that is somewhat different: https://opensourceebikefirmware.bitbucket.io/ https://opensourceebikefirmware.bitbucket.io/development/
* And the wiki of this repo: https://github.com/stancecoke/BMSBattery_S_controllers_firmware/wiki

It's very unclear what is outdated and what isn't.

I propose the following:
1. Start a new branch in this repo with all commits from the previous repo. This way all commits will be preserved in case somebody needs them.
2. Look through the [issues](https://github.com/OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware/issues) in the previous repo. File new tickets here for anything that is still relevant.
3. Remove the previous repo.
4. GitHub will automatically redirect to this fork, and this fork will become the main repo.

I can do most of that if given enough permissions. I also suggest to rename this repo to “OpenKT” or something that makes sense. I have no idea what's “BMSBattery”, and probably a lot of other users don't. Again, github will add redirects from the previous repo.

As for the documentation, it's a bit harder. I guess all existing info should be pulled into the wiki and previous doc sites should redirect to it. I can also work on that if you let me.

**Comment by casainho** [comment]
I started the project but then I did abandon it because I do not use KT motor controller anymore. Stancecoke and other developers continued the devolopment and help users on the forum.

If you want to assume the maintenance and development of the project, I can give you write access.
Note that I am working on TSDZ2 motor that has the same STM8 microcontroller as also I am working on the displays and now on a wireless board for EBike wireless standard on ANT+ and Bluetooth.

If I had to change, I would move the documentation to the regular MD files and not use the wiki, because on regular MD files anyone can make a pull request just like if is a regular code pull request. What is lost is the automatic generation of TOC that wiki pages does.

If you want to maintain the project, you will also need to be a developer for the motor controller code, are you ready for that??

**Comment by AlexDaniel** [comment]
> Note that I am working on TSDZ2 motor that has the same STM8 microcontroller

I've seen that, but I have always been curious why it was split into a different repo instead of generalizing common pieces of code and just rewriting the differences. In the long maybe I'd prefer the repos to be merged together, but it's a bit early to talk about that…

> If I had to change, I would move the documentation to the regular MD files and not use the wiki, because on regular MD files anyone can make a pull request just like if is a regular code pull request

People can edit wikis without making a pull request (just click Edit).

> If you want to assume the maintenance and development of the project, I can give you write access.

Now that I think about it, I'd also like to be able to do some tweaks for the Color_LCD. Can you create a “KT team” in [OpenSource-EBike-firmware org](https://github.com/OpenSource-EBike-firmware) with access to Color_LCD and BMSBattery_S_controllers_firmware repos?

> If you want to maintain the project, you will also need to be a developer for the motor controller code, are you ready for that??

Well, in open-source, it always comes down to the amount of free time developers have… let me start cleaning some things up and let's see how far I get. I don't know much about motor control itself, just some basics (e.g. see my [reverse engineering success](https://endless-sphere.com/forums/viewtopic.php?p=1546416#p1546416)).


Is there any place where you guys chat besides the forums?

**Comment by Xnyle** [comment]
Just my two cents b4 someone starts making bad decisions:

This repo has diverged so much from the original one that merging something would be a real pain (assuming you don't want to break anything that's currently working and in use; which you inevitably will)

It started as a fork stancecoke maintained and then I reworked a lot of stuff for features I wanted including live config via app.

Lately there have been some Bugfix forks but I never found the time to merge them (cause I also have to test them first)

The overall code quality (from a software developers point of view) is still very poor, the toolchain is also rather horrible.

But  it is what it is. Just what you get when electrical engineers starts to program stuff (no offense) and then other guys come along with different approaches.

I for instance have only a faint idea what I'm doing regarding the actual commutation algorithm, so without the electrical engineer there would be no code at all to complain about.

Again, it is what it is ;-)

If you are that guy who is expert in electrical engineering, software developement in general and app dev in specific plus ux design on top of that and also have a ton of spare time, go ahead.

Otherwise don't burn your fingers. There's nothing worse than yet another fork that introduces new "features" but breaks old ones, because then the next guy, even more confused about forks comes along ;-)

**Comment by AlexDaniel** [comment]
> This repo has diverged so much from the original one that merging something would be a real pain (assuming you don't want to break anything that's currently working and in use; which you inevitably will)

Noted.

> But it is what it is. Just what you get when electrical engineers starts to program stuff (no offense) and then other guys come along with different approaches.

Yeah, I noticed exactly that. But I don't think there's anything unfixable as long as we take it slow and step by step.

> If you are that guy who is expert in electrical engineering, software developement in general and app dev in specific plus ux design on top of that and also have a ton of spare time, go ahead.

Well… you can't really have that. Surely I work in all these areas, maybe more so in software development, but essentially everyone who does something like that ends up being a jack of all trades but master of none.

**Comment by Xnyle** [comment]
Step by step, yes.

First step would be to backport the crash bugfixes (related to controller overload on floating point calculations). stancecoke fixed that on some branch I can't find anymore 6 months ago. I never found the time to do that.

Also the x4throttle branch could be merged it should work out of the box.

And then there is apparently a new Java tool?

I should visit the forum....

I personally have two bikes now that are working fine without crashes, so I've become hesitant to merge or try out anything the last couple of months (still remember all the hassle and time spent to get it working perfectly like it is now).

**Comment by casainho** [comment]
> > Note that I am working on TSDZ2 motor that has the same STM8 microcontroller
> 
> I've seen that, but I have always been curious why it was split into a different repo instead of generalizing common pieces of code and just rewriting the differences. In the long maybe I'd prefer the repos to be merged together, but it's a bit early to talk about that…

About different repo:
Stancecoke continued the development and I always wanted to do the code in a different way he did, I always wanted only one interrupt for the PWM motor controller only and do motor current controller on that same interrupt, so, only one piece of code running on the interrupt and other on slow main loop. On TSDZ2, this is being working well - I think this approach is more secure for doing development, as long the interrupt does not stop, the motor control should not stop and so no risk for immediately burn of the MOSFETs / motor controller.

> > If I had to change, I would move the documentation to the regular MD files and not use the wiki, because on regular MD files anyone can make a pull request just like if is a regular code pull request
> 
> People can edit wikis without making a pull request (just click Edit).

I now prefer the pull request as that helps me to track the changes. Also, I found the need for users to upload pictures on a different repo than wiki which makes more difficult to understand and no one has access to upload pictures other than the developers. Well, wiki or markdown files, both are good enough for documentation on this projects.

> > If you want to assume the maintenance and development of the project, I can give you write access.
> 
> Now that I think about it, I'd also like to be able to do some tweaks for the Color_LCD. Can you create a “KT team” in [OpenSource-EBike-firmware org](https://github.com/OpenSource-EBike-firmware) with access to Color_LCD and BMSBattery_S_controllers_firmware repos?

Yes I can but I did not understand why you wanted to do tweaks for the Color_LCD / displays firmware, since I guess you have not display and TSDZ2 motor, right? what is your plan?

I do think that SW102 and 860C displays are good ones for EBikes and would be great to use with KT OpenSource firmware.

And don't forget the wireless EBike standard, wireless remote buttons, etc.


> Is there any place where you guys chat besides the forums?

We used https://gitter.im/OpenSource-EBike/community?at=5d977a34b385bf2cc6729a4b but not anymore. I would not mind to use other option, as gitter app on Android notifications did not work for me.

**Comment by casainho** [comment]
And other thing I would improve now was using Code Studio for flash and debug. I always used and older version of Eclipse and was a PITA to make it working for flash and debug the STM8 - with my current recent experience on Code Studio, I am sure it will be easy to make it working and so help other new developers to join the project.

Here my notes for Configure Code Studio IDE for firmware development, flash and debug for the TSDZ2 wireless board (I am sure you can easily adapt for STM8):

https://github.com/OpenSource-EBike-firmware/TSDZ2_wireless/blob/master/documentation/development-flash_and_debug_firmware.md

![image](https://user-images.githubusercontent.com/147128/87227450-f158ed80-c392-11ea-945e-40559f75ec36.png)

![image](https://user-images.githubusercontent.com/147128/87227477-21a08c00-c393-11ea-9c13-c763c10fca8d.png)

**Comment by AlexDaniel** [comment]
> Yes I can but I did not understand why you wanted to do tweaks for the Color_LCD / displays firmware, since I guess you have not display and TSDZ2 motor, right? what is your plan?

Simply because I also want to run custom firmware on the LCD too. Any reason why the firmware for the LCD would be specific for just TSDZ2? To be clear, I have KT controller and LCD8H display. Now that I look at it, however, I see that it doesn't seem to be supported yet? Anyway, please clarify. What I don't want for sure is creating a yet another repository just because the hardware is different.

**Comment by AlexDaniel** [comment]
> now prefer the pull request as that helps me to track the changes. Also, I found the need for users to upload pictures on a different repo than wiki which makes more difficult to understand and no one has access to upload pictures other than the developers.

Just as a potentially useful hint, wikis are repos too. For example, you can clone https://github.com/stancecoke/BMSBattery_S_controllers_firmware.wiki.git and do any operations that you'd normally do to a repo.

**Comment by casainho** [comment]
> LCD8H

Yes, LCD8H is not supported. I have one with me and I found it has no RTC for having clock. And after all this time, the 860C display is really better because has a very bright display and colors under sunlight, much brighter than my good smartphone and even my Garmin recent GPS model.

And for 860C, we have tools to flash the firmware using the original wires, using the original bootloader so much easier for final user to install the firmware, no need to open and destroy the case and water prof.

And 850C/860C display are way more popular because they are for Bafang motors, so they are easy to source, to be found on many online shops including the cables.

And now you have the advantage that 860C display firmware is fully developed and is easy to add support for other motor controller.
