### ISSUE TITLE
acs712 v acs711 on kte-9S5-E

### ISSUE THREAD

**Issue by JamesCordell** [stancecoke/BMSBattery_S_controllers_firmware#17]
I intend to perform the current sensor modification. Do you have any advice. I noticed that in the guide the acs712 is used, I see that in this later revision of the board the footprint caters for a acs711 for U6 (with 10 legs ) do my observations look correct and should this work?

https://www.hobbytronics.co.uk/datasheets/ACS711.pdf

https://www.sparkfun.com/datasheets/BreakoutBoards/0712.pdf

![IMG_20200909_222406](https://user-images.githubusercontent.com/1229139/92661476-9e4cd980-f2f4-11ea-93a0-e3ec9b0ed7f8.png)
![IMG_20200909_222345](https://user-images.githubusercontent.com/1229139/92661541-c3414c80-f2f4-11ea-9e37-545aacb9f415.png)
![IMG_20200909_222318](https://user-images.githubusercontent.com/1229139/92661602-de13c100-f2f4-11ea-9fb3-bf73bbb43e1c.png)

**Comment by stancecoke** [comment]
please report at endless sphere, if your mod was successful!
https://endless-sphere.com/forums/viewtopic.php?f=30&t=87870

**Comment by kaleo10** [comment]
> I intend to perform the current sensor modification. Do you have any advice. I noticed that in the guide the acs712 is used, I see that in this later revision of the board the footprint caters for a acs711 for U6 (with 10 legs ) do my observations look correct and should this work?
> 
> https://www.hobbytronics.co.uk/datasheets/ACS711.pdf
> 
> https://www.sparkfun.com/datasheets/BreakoutBoards/0712.pdf
> 
> ![IMG_20200909_222406](https://user-images.githubusercontent.com/1229139/92661476-9e4cd980-f2f4-11ea-93a0-e3ec9b0ed7f8.png) ![IMG_20200909_222345](https://user-images.githubusercontent.com/1229139/92661541-c3414c80-f2f4-11ea-9e37-545aacb9f415.png) ![IMG_20200909_222318](https://user-images.githubusercontent.com/1229139/92661602-de13c100-f2f4-11ea-9fb3-bf73bbb43e1c.png)

Where can I get this controller? 
thanks

**Comment by consp** [comment]
I know the issue is closed but it shows up quite high if you search for this specific controller.

I have one with the "711" installed, might require a change, since it's 45-68mV/A intread of the more usual 70-100. And you might also have a version with ~90mV/A. It depends and it's impossible to know by the markings on the chip as it is a clone. You should experiment with an external measurement. The zero-current voltage should be half of Vcc for the 45-68mV/A  variant. (45mV/A is at 3.3v, 68mV/A at 5v). I'm not sure if it needs changes or not, the B phase current is not manipulated with calibration values afaik.

Mine also had a bridge between the B/green phase and the supply pad. Why I have no clue since it will make all measurements useless. Cut it and you get current measurements.

Another issue with it is the 51 ohm resistor on the output of the lights module. Te FET (which is a FET normally used in CRT tv's) can easily supply 1A and since I have lights with their own regulators and are significantly more energetic than the standard ones it will kill the resistor quickly since the 1W resistor will take more than a few A's and cook it. Unless you like the smell of burned resistor I advise you to bridge the resistor if you use lights with voltage regulators and more power than normal. Do not connect LEDs streight to it when you remove it, you will kill the LEDs.
