### ISSUE TITLE
Help needed KT48svprk-sjt02l

### ISSUE THREAD

**Issue by zimivanende** [stancecoke/BMSBattery_S_controllers_firmware#30]
When using this sinewave controller I get pulses when applying throttle. Sometimes it doesn't happen, but most of the time this issue is present.

When Inuse a dual mode version of the controller (i have both) the engine uses more power, 5pkh higher top speed but also the engine gets hotter aswel. With this controller the pusling issue is not present.

Any idea what this could be? What setting I could look at to resolve this?

https://youtu.be/hMDEblUDSA4

![20230413_102809](https://user-images.githubusercontent.com/44968400/231701091-8e6f0637-3eae-4e78-8732-7015026c8565.jpg)

**Comment by Xnyle** [comment]
Wiki Chapter 4, GAIN P/GAIN I

**Comment by zimivanende** [comment]
What are the min and max values for these gains?

**Comment by Xnyle** [comment]
I assume 0-1 but I'm no expert either, can't provide further support.

**Comment by zimivanende** [comment]
Thanks it was solved by setting P gain to 0.9. strangely enough a higher gain removed the oscillating

**Comment by zimivanende** [comment]
It seems it now occurs around 38kph.

**Comment by zimivanende** [comment]
When I increase the I gain the oscillating happens throughout all speeds again. 

I tried a p gain of 0.7 and again around 34-38kph it starts oscillating.

Any ideas what this could be? P gain up or down? Motor angle maybe?

**Comment by dot-rod** [comment]
Hi. I have the exact same controller running kt-3 controller, 1500w motor on stock firmware. I have no such pulsing issues as you but do find it to be sub par.
It is hard to setup, stock settings are for pas controll not handle bar throttle, it is very aggressive with no speed control. Changing p3 to 0 activates the 'gears' which tames it a little, crushing at 33kphr on pas 2 at 300w. The main issue is top speed which seems low at 50kphr, my 1000w mtb running sw900 and square wave controller does 56kphr, so this should do 60+.

My only suggestion for your issue is the hall effects are wired incorrectly, this will cause excess heat, rough running and poor power consumption.

Regards,
Dot_rod

**Comment by dot-rod** [comment]
Test gadget

https://endless-sphere.com/sphere/threads/how-to-determine-the-wiring-for-a-brushless-motor.3484/

**Comment by dot-rod** [comment]
https://endless-sphere.com/sphere/threads/need-help-first-build-with-kt-lcd3.96845/

![Screenshot_2023-04-29_021849](https://user-images.githubusercontent.com/131939728/235174019-af5bac0e-2a76-46cc-a4f0-eb101d83d41a.jpg)
